apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - storeserviceat.yml
#  - storeserviceat-service.yaml
#  - storeserviceat-ingress.yaml
images:
  - name: petstorevet
    newName: leopedroza98/petstorevet
    newTag: latest