apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - petstorevet.yml
  - petstorevet-service.yaml
  - petstorevet-ingress.yaml
images:
  - name: petstorevet
    newName: leopedroza98/petstorevet
    newTag: "221225.a532ce9"