apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstorevet
  labels:
    app: petstorevet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstorevet
  template:
    metadata:
      labels:
        app: petstorevet
    spec:
      containers:
        - name: petstorevet
          image: petstorevet
          env:
            - name: MySqlConnection__MysqlConnectionString
              valueFrom:
                secretKeyRef:
                  name: pet-store-db-user
                  key: connection-string